source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'classifier-reborn'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-toc'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'mini_racer'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'feedjira'
    gem 'httparty'
end
# Standard library gems removed from Ruby 3.5+ defaults — required by older
# plugins (jekyll-twitter-plugin needs ostruct; others may need these too).
gem 'ostruct'
gem 'logger'
gem 'csv'
gem 'base64'
gem 'bigdecimal'
gem 'mutex_m'
gem 'observer'
